// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEvyKXa3DRjJcjY-AEldgCZmq77vMsts',
    appId: '1:1065987171723:web:b741f6775c23477692bb8e',
    messagingSenderId: '1065987171723',
    projectId: 'mobilelibrary-6856f',
    authDomain: 'mobilelibrary-6856f.firebaseapp.com',
    databaseURL: 'https://mobilelibrary-6856f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilelibrary-6856f.appspot.com',
    measurementId: 'G-6JK22R7J94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yf_jJg4d2yJ7qF9vDKZ7Ztc9vJc5Mh4',
    appId: '1:1065987171723:android:00fb1052985361a392bb8e',
    messagingSenderId: '1065987171723',
    projectId: 'mobilelibrary-6856f',
    databaseURL: 'https://mobilelibrary-6856f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilelibrary-6856f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdujPhzHhiApKEnkzl0DNtAWKr6oqmSs',
    appId: '1:1065987171723:ios:a973d1b7faf230d792bb8e',
    messagingSenderId: '1065987171723',
    projectId: 'mobilelibrary-6856f',
    databaseURL: 'https://mobilelibrary-6856f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilelibrary-6856f.appspot.com',
    iosBundleId: 'com.example.mobileLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdujPhzHhiApKEnkzl0DNtAWKr6oqmSs',
    appId: '1:1065987171723:ios:150de8f248677d1792bb8e',
    messagingSenderId: '1065987171723',
    projectId: 'mobilelibrary-6856f',
    databaseURL: 'https://mobilelibrary-6856f-default-rtdb.firebaseio.com',
    storageBucket: 'mobilelibrary-6856f.appspot.com',
    iosBundleId: 'com.example.mobileLibrary.RunnerTests',
  );
}
